uploads = []
generated = []

[[outputs]]
id = "sqhk9q4VfdwZ2remeiC2I"
uri = "file://生日通-本地部署文档.md"
type = "text"
title = "生日通 · 本地服务器部署文档"

[[outputs]]
id = "AZufepMqrZP1tDMvFWq3Q"
uri = "file://PRD.md"
type = "text"
title = "生日通 · 产品需求文档 v1.0"
